Feat sem equiv
SEAL-Self-Assessment-and-Learning/algo-learn pull request #56
Opened 2024-12-12 20:34 UTC by Fabianstw

[Testing location](https://tcs.uni-frankfurt.de/algo-learn-testing/refs_heads_feat-sem-equiv/en)

Generator that requires the user to determine which expressions are equivalent or not.
Provides different variants for the number of different variables.

### Propositional logic helper function
- `expressionsDifferent`: Checks if no two expressions in a list are equivalent.

2025-02-19 20:00 UTC, AbcAeffchen requested changes
Question looks good. Only some minor issue.

2025-02-19 20:00 UTC, AbcAeffchen commented on shared/src/question-generators/propositional-logic/semanticEquivalence.ts
> +import { max, min } from "mathjs"
Use JS functions `Math.max` and `Math.min` instead.

2025-02-19 20:00 UTC, AbcAeffchen commented on shared/src/question-generators/propositional-logic/semanticEquivalence.ts
> +    text: "Given the following boolean expressions: {{0}} Determine which **equivalences** are `{{1}}`:",
"Given the following propositional logic formulas: {{0}} Decide which of the following semantic equivalences are {{1}}:"

The other texts should also changed to fit this one.

2025-02-19 20:00 UTC, AbcAeffchen commented on shared/src/question-generators/propositional-logic/semanticEquivalence.ts
> +    text: "Bestimme welche der folgenden Äquivalenzen `{{0}}` sind:",
The text is not equivalent to the English version.

2025-02-19 20:00 UTC, AbcAeffchen commented on shared/src/utils/propositionalLogic/propositionalLogic.ts
> +export function expressionsDifferent(expressions: SyntaxTreeNodeType[]): boolean {
`arePairwiseInequivalent` would be a better name.

2025-02-19 20:00 UTC, AbcAeffchen commented on shared/src/utils/propositionalLogic/propositionalLogic.ts
> +    throw new Error("At least two expressions are required for comparison.")
just return `true`. Simplifies the usage of the function.

2025-02-19 20:00 UTC, AbcAeffchen commented on shared/src/question-generators/propositional-logic/semanticEquivalence.ts
> +    generateRandomExpression(random, numLeaves + random.int(-1, 2), varNames.slice(0, numVars)),
Can be simplified if `expressionsDifferent` is changed according to the comment.
Initialize to the empty list and start the for loop at `i=0`.

2025-02-20 06:41 UTC, Fabianstw commented on shared/src/question-generators/propositional-logic/semanticEquivalence.ts
> +    text: "Given the following boolean expressions: {{0}} Determine which **equivalences** are `{{1}}`:",
Change those to:
```
description: "Determine which formulas are equivalent",
size: "Number of variables",
```

2025-02-20 06:43 UTC, Fabianstw commented on shared/src/question-generators/propositional-logic/semanticEquivalence.ts
> +    text: "Bestimme welche der folgenden Äquivalenzen `{{0}}` sind:",
Don't know what happened there 😅

2025-02-20 13:30 UTC, AbcAeffchen commented
Looks god now.

2025-02-20 13:32 UTC, AbcAeffchen commented on shared/src/question-generators/propositional-logic/semanticEquivalence.ts
> +import { max, min } from "mathjs"
This is still in there if I see it right.

2025-02-20 14:08 UTC, merged